# Generated by Django 4.1.3 on 2023-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CornGrainYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of the harvest', unique=True)),
                ('corn_yield', models.FloatField(help_text='Corn grain yield in the United States (measured in 1000s of megatons)')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Weather station identifier', max_length=30)),
                ('year', models.PositiveSmallIntegerField(help_text='statistics were calculated for this year')),
                ('max_temp_avg', models.FloatField(help_text='Average maximum temperature (in degrees Celsius)', null=True)),
                ('min_temp_avg', models.FloatField(help_text='Average minimum temperature (in degrees Celsius)', null=True)),
                ('total_precipitation', models.FloatField(help_text='Total accumulated precipitation (in centimeters', null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['station_id', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Weather station identifier', max_length=30)),
                ('date', models.DateField(help_text='Date measured')),
                ('max_temp', models.FloatField(help_text='The maximum temperature for that day (in tenths of a degree Celsius)')),
                ('min_temp', models.FloatField(help_text='The minimum temperature for that day (in tenths of a degree Celsius)')),
                ('precipitation', models.FloatField(help_text='The amount of precipitation for that day (in tenths of a millimeter)')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(fields=('station_id', 'date'), name='unique station data for particular day'),
        ),
        migrations.AddConstraint(
            model_name='dataanalysis',
            constraint=models.UniqueConstraint(fields=('station_id', 'year'), name='unique station data for particular year'),
        ),
    ]
