# Generated by Django 4.1.3 on 2023-03-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CornGrainYield',
        ),
        migrations.AlterModelTable(
            name='weather',
            table='Weather',
        ),
    ]
